from typing import Optional

from google.adk.agents.callback_context import CallbackContext
from google.adk.models.llm_response import LlmResponse
from google.adk.plugins.base_plugin import BasePlugin
from loguru import logger


class ContinuationPlugin(BasePlugin):
    """Detects when the LLM outputs an empty payload due to overload and prompts the user to continue."""

    def __init__(self) -> None:
        super().__init__(name="continuation_plugin")

    async def after_model_callback(
        self,
        *,
        callback_context: CallbackContext,
        llm_response: LlmResponse,
    ) -> Optional[LlmResponse]:
        """Intercepts empty model responses to prevent silent failures.

        Args:
            callback_context: CallbackContext -> Context of the current agent call.
            llm_response: LlmResponse -> The response generated by the model.

        Returns:
            Optional[LlmResponse] -> The modified response, or None if no modification is needed.
        """
        # If the response has text content or tool calls, it's a valid response (including OAuth requests).
        # We only want to intercept when BOTH are missing (the silent failure mode).
        if llm_response.content or llm_response.tool_calls:
            return None

        logger.warning(
            "ContinuationPlugin - Detected empty LLM payload (silent failure). "
            "Injecting continuation message."
        )

        # The model failed to process the request (likely due to payload size limits).
        # We inject a user-friendly message asking them to write "continue".
        llm_response.content = "I was unable to complete the request in a single pass. Please write **'continue'** to complete the tasks."

        return llm_response
