from typing import Optional

from google.adk.agents.callback_context import CallbackContext
from google.adk.models.llm_response import LlmResponse
from google.adk.plugins.base_plugin import BasePlugin
from google.genai import types
from loguru import logger


class ContinuationPlugin(BasePlugin):
    """Detects when the LLM outputs an empty payload due to overload and prompts the user to continue."""

    def __init__(self) -> None:
        super().__init__(name="continuation_plugin")

    async def after_model_callback(
        self,
        *,
        callback_context: CallbackContext,
        llm_response: LlmResponse,
    ) -> Optional[LlmResponse]:
        """Intercepts empty model responses to prevent silent failures.

        Args:
            callback_context: CallbackContext -> Context of the current agent call.
            llm_response: LlmResponse -> The response generated by the model.

        Returns:
            Optional[LlmResponse] -> The modified response, or None if no modification is needed.
        """
        has_tool_calls = bool(llm_response.get_function_calls())

        has_text = False
        if llm_response.content and llm_response.content.parts:
            for part in llm_response.content.parts:
                if getattr(part, "text", None):
                    has_text = True
                    break

        if has_text or has_tool_calls:
            return None

        logger.warning(
            "ContinuationPlugin - Detected empty LLM payload (silent failure). "
            "Injecting continuation message."
        )

        # The model failed to process the request (likely due to payload size limits).
        # We inject a user-friendly message asking them to write "continue".
        message = "I was unable to complete the request in a single pass. Please write **'continue'** to complete the tasks."
        if llm_response.content is None:
            llm_response.content = types.Content(
                role="model", parts=[types.Part.from_text(text=message)]
            )
        else:
            llm_response.content.parts = [types.Part.from_text(text=message)]

        return llm_response
