substitutions:
  _LOCATION: us-central1
  _REPO_NAME: mcp-servers
  _SERVICE_NAME: ui-frontend

steps:

  # Step 1: Initialize Terraform
  - name: 'hashicorp/terraform:1.12.2'
    id: 'tf-init'
    entrypoint: 'sh'
    dir: 'terraform/ui_frontend_resources'
    args:
      - '-c'
      - |
        terraform init \
          -backend-config="bucket=${PROJECT_ID}-terraform-state" \
          -backend-config="prefix=terraform/state/ui-frontend-resources"

  # Step 2: Docker Build for Prod
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args: [
      'build', 
      '-t', '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}', 
      '-t', '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest', 
      '-f', 'ui/frontend/Dockerfile', 
      '.'
    ]

  # Step 3: Docker Push for Prod
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        docker push ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}
        docker push ${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/${_SERVICE_NAME}:latest

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'iap-permissions'
    args: ['projects', 'add-iam-policy-binding', '${PROJECT_ID}', '--member=serviceAccount:${_SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com', '--role=roles/iap.admin', '--condition=None', '--quiet', '--format=none']

  # Step 4: Full Terraform Plan
  - name: 'hashicorp/terraform:1.12.2'
    id: 'tf-plan'
    args:
      - 'plan'
      - '-var=ui_frontend_cloud_run_image_tag=${COMMIT_SHA}'
      - '-var=project_id=${PROJECT_ID}'
      - '-var=main_region=${_LOCATION}'
      - '-out=tfplan'
    dir: 'terraform/ui_frontend_resources'

  # Step 5: Full Terraform Apply
  - name: 'hashicorp/terraform:1.12.2'
    id: 'tf-apply'
    args: ['apply', '-auto-approve', 'tfplan']
    dir: 'terraform/ui_frontend_resources'

serviceAccount: 'projects/${PROJECT_ID}/serviceAccounts/${_SA_NAME}@${PROJECT_ID}.iam.gserviceaccount.com'

options:
  logging: CLOUD_LOGGING_ONLY
