data "google_project" "project" {
  project_id = var.project_id
}

locals {
  artifact_registry_region = coalesce(var.artifact_registry_region, var.main_region)
}

module "artifact_registry" {
  source     = "../base_modules/artifact-registry"
  project_id = var.project_id
  name       = var.artifact_registry_name
  location   = local.artifact_registry_region

  format = {
    docker = {
      standard = {}
    }
  }
}

resource "google_bigquery_dataset" "knowledge_base" {
  dataset_id    = "knowledge_base"
  friendly_name = "knowledge_base"
  description   = "Enterprise Knowledge Base dataset"
  location      = var.main_region
}

resource "google_bigquery_table" "documents_chunks" {
  dataset_id = google_bigquery_dataset.knowledge_base.dataset_id
  table_id   = "documents_chunks"

  schema = <<EOF
[
  {
    "name": "chunk_id",
    "type": "STRING",
    "mode": "REQUIRED",
    "description": "UUID of the chunk"
  },
  {
    "name": "document_id",
    "type": "STRING",
    "mode": "NULLABLE",
    "description": "Foreign Key to metadata"
  },
  {
    "name": "chunk_data",
    "type": "STRING",
    "mode": "REQUIRED",
    "description": "Raw text of the chunk"
  },
  {
    "name": "gcs_uri",
    "type": "STRING",
    "mode": "REQUIRED",
    "description": "Original GCS URI of the document"
  },
  {
    "name": "filename",
    "type": "STRING",
    "mode": "REQUIRED",
    "description": "Filename of the document"
  },
  {
    "name": "structural_metadata",
    "type": "JSON",
    "mode": "NULLABLE",
    "description": "Section headers, list context"
  },
  {
    "name": "page_number",
    "type": "INTEGER",
    "mode": "NULLABLE",
    "description": "Source page in the document"
  },
  {
    "name": "embedding",
    "type": "FLOAT64",
    "mode": "REPEATED",
    "description": "Vector generated by BQML"
  },
  {
    "name": "created_at",
    "type": "TIMESTAMP",
    "mode": "REQUIRED",
    "description": "Timestamp of ingestion"
  },
  {
    "name": "vectorized_at",
    "type": "TIMESTAMP",
    "mode": "NULLABLE",
    "description": "Execution time of BQML job"
  }
]
EOF
}

resource "google_storage_bucket" "kb_landing_zone" {
  name          = "${var.project_id}-kb-landing-zone"
  location      = var.main_region
  force_destroy = true

  uniform_bucket_level_access = true
}

resource "google_storage_bucket_object" "ingested_folder" {
  name    = "ingested/"
  content = "placeholder"
  bucket  = google_storage_bucket.kb_landing_zone.name
}

resource "google_storage_bucket_object" "processed_folder" {
  name    = "processed/"
  content = "placeholder"
  bucket  = google_storage_bucket.kb_landing_zone.name
}
