import datetime
from typing import Optional, Protocol

from google.cloud import storage
from loguru import logger

from .config import SHAREPOINT_SERVER_CONFIG


class ReadableStream(Protocol):
    """Protocol for file-like objects accepted by the GCS SDK."""

    def read(self, size: int = -1) -> bytes:
        """
        Reads bytes from the wrapped stream.

        Args:
            size: int -> Number of bytes to read from the stream.

        Returns:
            bytes -> Bytes read from the stream.
        """
        ...


class GCSConnector:
    """Handles zero-copy file streaming to the GCS Landing Zone."""

    def __init__(self) -> None:
        """
        Initializes a GCS client and landing-zone bucket handle.

        Args:
            None

        Returns:
            None -> Initializes the connector.
        """
        self.client = storage.Client()
        self.bucket_name = SHAREPOINT_SERVER_CONFIG.landing_zone_bucket
        self.bucket = self.client.bucket(self.bucket_name)
        logger.info("GCSConnector initialized for bucket %s", self.bucket_name)

    def upload_stream(
        self,
        file_obj: ReadableStream,
        content_type: str,
        app_name: str,
        user_id: str,
        session_id: str,
        filename: str,
        size: Optional[int] = None,
    ) -> str:
        """
        Uploads a file-like object directly to the Landing Zone bucket.

        Args:
            file_obj: ReadableStream -> A stream containing the file bytes.
            content_type: str -> The MIME type of the file.
            app_name: str -> The name of the calling application or agent.
            user_id: str -> The unique identifier of the user.
            session_id: str -> The current session or conversation ID.
            filename: str -> The original filename to preserve.
            size: Optional[int] -> Optional explicit file size for unseekable streams.

        Returns:
            str -> The canonical GCS URI of the uploaded object.
        """
        timestamp = datetime.datetime.now(datetime.timezone.utc).strftime(
            "%Y%m%dT%H%M%SZ"
        )
        object_name = (
            f"{app_name}/{user_id}/{session_id}/sharepoint-{timestamp}-{filename}"
        )
        blob = self.bucket.blob(object_name)

        logger.info(
            "Starting SharePoint stream upload to gs://%s/%s",
            self.bucket_name,
            object_name,
        )
        if size is None:
            blob.upload_from_file(file_obj, content_type=content_type, rewind=False)
        else:
            blob.upload_from_file(
                file_obj,
                content_type=content_type,
                size=size,
                rewind=False,
            )

        self._grant_user_access(app_name, user_id)
        return f"gs://{self.bucket_name}/{object_name}"

    def _grant_user_access(self, app_name: str, user_id: str) -> None:
        """
        Grants the user object-admin access only to their landing-zone namespace.

        Args:
            app_name: str -> The name of the calling application or agent.
            user_id: str -> The unique identifier of the user.

        Returns:
            None -> Mutates the bucket IAM policy if the binding is absent.
        """
        resource_prefix = (
            f"projects/_/buckets/{self.bucket_name}/objects/{app_name}/{user_id}/"
        )
        condition_expr = f'resource.name.startsWith("{resource_prefix}")'
        member = f"user:{user_id}"

        iam_policy = self.bucket.get_iam_policy(requested_policy_version=3)
        iam_policy.version = 3

        already_granted = any(
            binding.get("role") == "roles/storage.objectAdmin"
            and member in binding.get("members", set())
            and (binding.get("condition") or {}).get("title")
            == "uploader-folder-access"
            and (binding.get("condition") or {}).get("expression") == condition_expr
            for binding in iam_policy.bindings
        )
        if already_granted:
            logger.debug("Folder IAM binding already exists for %s", member)
            return

        iam_policy.bindings.append(
            {
                "role": "roles/storage.objectAdmin",
                "members": {member},
                "condition": {
                    "title": "uploader-folder-access",
                    "description": (
                        f"Auto-generated by SharePoint MCP Server for user {user_id}"
                    ),
                    "expression": condition_expr,
                },
            }
        )
        self.bucket.set_iam_policy(iam_policy)
        logger.info("Granted landing-zone namespace access to %s", member)
