from typing import Any

from loguru import logger

import google.auth
import google.oauth2.id_token
from google.auth.transport.requests import Request
from google.adk.agents.readonly_context import ReadonlyContext


def get_id_token(audience: str) -> str | None:
    """
    Generate a valid ID token to call a GCP service such as Cloud Run.

    It first tries the metadata server (when running on GCP) and then falls back to
    local ADC credentials for development.
    """
    logger.info(f"Generating ID token for audience: {audience}")
    request = Request()
    try:
        logger.debug(
            f"Retrieving ID token from metadata server for audience {audience}"
        )
        id_token = google.oauth2.id_token.fetch_id_token(request, audience)
        logger.debug("ID token successfully retrieved from metadata server")
        return id_token
    except Exception as exc:
        logger.warning(f"Metadata-server ID token retrieval failed: {exc}")

    try:
        logger.debug("Retrieving ID token from local ADC credentials")
        credentials, _ = google.auth.default()
        credentials.refresh(request)
        id_token = getattr(credentials, "id_token", None)
        if id_token:
            logger.debug("ID token retrieved from local ADC credentials")
            return id_token
        logger.warning("ADC credentials did not yield an ID token")
    except Exception as exc:
        logger.warning(f"Unable to obtain ID token from local ADC credentials: {exc}")

    return None


def _get_state_value(state: Any, key: str) -> Any:
    """Safely reads a value from ADK State-like objects or dictionaries."""
    if state is None:
        return None

    if isinstance(state, dict):
        return state.get(key)

    get_method = getattr(state, "get", None)
    if callable(get_method):
        try:
            return get_method(key)
        except Exception:
            pass

    try:
        return state[key]
    except Exception:
        return None


def _describe_state_keys(state: Any) -> list[str]:
    """Best-effort state key listing without assuming ADK State is a dict."""
    if state is None:
        return []

    if isinstance(state, dict):
        return [str(key) for key in state.keys()]

    keys_method = getattr(state, "keys", None)
    if callable(keys_method):
        try:
            return [str(key) for key in keys_method()]
        except Exception:
            pass

    for attr_name in ("value", "_value", "_state", "_data"):
        value = getattr(state, attr_name, None)
        if isinstance(value, dict):
            return [str(key) for key in value.keys()]

    try:
        return [str(key) for key in state]
    except Exception:
        return []


def get_ge_oauth_token(readonly_context: ReadonlyContext, auth_id: str) -> str | None:
    """
    Inject the generated OAuth token that is generated by Gemini Enterprise when a Resource ID
    is created.

    Code adapted from: https://github.com/google/adk-docs/issues/1001#issuecomment-3894834825

    Args:
        readonly_context: The readonly context of the agent.
        auth_id: The ID of the resource id in Gemini Enterprise.

    Returns:
        str | None: The OAuth token if found, None otherwise.
    """
    logger.info(f"Getting OAuth token for {auth_id = }")
    state = getattr(readonly_context, "state", None)
    oauth_token = _get_state_value(state, auth_id)
    if oauth_token:
        logger.info("OAuth token found")
    else:
        logger.error("OAuth token not found")
        logger.error("Available state keys: {}", _describe_state_keys(state))

    return oauth_token
