name: Code Quality CI

on:
  pull_request:
    branches: [ main ]

jobs:
  pre-commit:
    name: Lint & Format (Python)
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1